# Generated by Django 3.0.5 on 2020-05-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('Host', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('Path', models.CharField(max_length=50, verbose_name='Путь до файла')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название сервиса')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(verbose_name='Содержание файла')),
                ('LastModified', models.DateTimeField(auto_now_add=True, verbose_name='Последнее изенение файла')),
                ('ConfigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coll_conf_ms.Config', verbose_name='Конфиг')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='ServiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coll_conf_ms.Service', verbose_name='Сервис'),
        ),
    ]
